// Authentication
export const SIGNIN_USER = "SIGNIN_USER";
export const SIGNIN_USER_SUCCESS = "SIGNIN_USER_SUCCESS";
export const SIGNOUT_USER = "SIGNOUT_USER";
export const SIGNOUT_USER_SUCCESS = "SIGNOUT_USER_SUCCESS";

// Movies
export const REQUEST_GET_MOVIES_LIST = "REQUEST_GET_MOVIES_LIST";
export const SUCCESS_GET_MOVIES_LIST = "SUCCESS_GET_MOVIES_LIST";
export const REQUEST_MOVIE = "REQUEST_MOVIE";
export const SUCCESS_MOVIE = "SUCCESS_MOVIE";
export const REQUEST_ADD_MOVIE = "REQUEST_ADD_MOVIE";
export const SUCCESS_ADD_MOVIE = "SUCCESS_ADD_MOVIE";
export const REQUEST_EDIT_MOVIE = "REQUEST_EDIT_MOVIE";
export const SUCCESS_EDIT_MOVIE = "SUCCESS_EDIT_MOVIE";
export const REQUEST_DELETE_MOVIE = "REQUEST_DELETE_MOVIE";
export const SUCCESS_DELETE_MOVIE = "SUCCESS_DELETE_MOVIE";
export const CHANGE_PAGE = "CHANGE_PAGE";
export const HIDE_LOADER = "HIDE_LOADER";